name: suncube_ai
description: "SunCube Ai Prototype app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  fl_chart: ^1.0.0
  provider: ^6.1.5
  lucide_icons_flutter: ^3.0.7
  get_storage: ^2.1.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
