// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'suncube_ai';
  static const String PROJECT_VERSION = '0.1.0';
  static const String FS01 = 'assets/fs01.png';
  static const String FS02 = 'assets/fs02.png';
  static const String FS03 = 'assets/fs03.png';
  static const String FS04 = 'assets/fs04.png';
}
